LinkHub/Controllers/LinksController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using AutoMapper;
using LinkHub.Models;
using LinkHub.Repositories;
using LinkHub.Services;
using LinkHub.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using SixLabors.ImageSharp;

namespace LinkHub.Controllers
{
    [Authorize(Roles = "Admin, Editor")]
    public class LinksController : Controller
    {
        private readonly ILinkRepository _linkRepository;
        private readonly IPageRepository _pageRepository;
        private readonly ICategoryRepository _categoryRepository;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly INotyfService _notyfService;
        private readonly ImageStorage _imageStorage;
        private readonly IMapper _mapper;

        public LinksController(ILinkRepository linkRepository,
            ICategoryRepository categoryRepository,
            IPageRepository pageRepository,
            UserManager<ApplicationUser> userManager,
            INotyfService notyfService,
            ImageStorage imageStorage,
            IMapper mapper)
        {
            _linkRepository = linkRepository;
            _categoryRepository = categoryRepository;
            _pageRepository = pageRepository;
            _userManager = userManager;
            _notyfService = notyfService;
            _imageStorage = imageStorage;
            _mapper = mapper;
            
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var user = await _userManager.GetUserAsync(User);
            var userId = user?.Id;

            if (userId == null)
            {
                return RedirectToAction("Login", "Account");
            }

            List<Link> links = await _linkRepository.GetLinksPerUserAsync(userId);
            List<Page> pages = await _pageRepository.GetPagePerUserAsync(userId);

            var linkIndexViewModel = new LinkIndexViewModel
            {
                Pages = pages,
                Links = links
            };

            return View(linkIndexViewModel);
        }

        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            var user = await _userManager.GetUserAsync(User);
            var userId = user?.Id;

            if (userId == null)
            {
                return RedirectToAction("Login", "Account");
            }

            var link = await _linkRepository.GetLinkAsync(id);
            if (link == null)
            {
                return Json(new { message = "Página não encontrada!" });
            }

            return PartialView("_Details", link);
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var user = await _userManager.GetUserAsync(User);
            var userId = user?.Id;

            if (userId == null)
            {
                return RedirectToAction("Login", "Account");
            }

            var pages = await _pageRepository.GetPagePerUserAsync(userId);            

            var linkView = new LinkViewModel
            {
                Pages = pages,
                Categories = new List<Category>()
            };
                        
            return PartialView("_Create", linkView);
        }

        [HttpGet]
        public async Task<IActionResult> FilterCategories(int pageId)
        {
            var categories = await _categoryRepository.GetCategoriesPerPageAsync(pageId);

            return Json(categories);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(LinkViewModel linkViewModel)
        {
            if (!ModelState.IsValid)
            {
                _notyfService.Warning("Preencha todos os campos obrigatórios.");
                return RedirectToAction("Index");
            }

            try
            {
                var link = _mapper.Map<Link>(linkViewModel);

                if (linkViewModel.Image != null)
                {
                    link.FileName = await _imageStorage.AddImageAsync(linkViewModel.Image);
                }

                await _linkRepository.Add(link);
                _notyfService.Success("Link adicionado com sucesso.");
            }
            catch (UnknownImageFormatException)
            {
                _notyfService.Error("Imagem não suportada! Adicione imagens do tipo JPEG, PNG, BMP ou Webp.");
            }
            catch (Exception ex)
            {
                _notyfService.Error("Ocorreu um erro ao adicionar o link: " + ex.Message);
            }

            return RedirectToAction("Index");
        }
                
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var user = await _userManager.GetUserAsync(User);
            var userId = user?.Id;
            if (userId == null)
            {
                return RedirectToAction("Login", "Account");
            }

            var link = await _linkRepository.GetLinkAsync(id);
            if (link == null)
            {
                return Json(new { message = "Link não encontrado!" });
            }

            if (link.Category == null)
            {
                return Json(new { message = "Categoria do link não encontrada!" });
            }

            var pageId = link.Category.PageId;

            var pages = await _pageRepository.GetPagePerUserAsync(userId);
            var categories = await _categoryRepository.GetCategoriesPerPageAsync(pageId);

            var linkViewModel = _mapper.Map<LinkViewModel>(link);

            linkViewModel.Pages = pages;
            linkViewModel.PageId = pageId;
            linkViewModel.Categories = categories;

            return PartialView("_Edit", linkViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(LinkViewModel linkViewModel)
        {
            if (!ModelState.IsValid)
            {
                _notyfService.Warning("Preencha todos os campos obrigatórios.");
                return RedirectToAction("Index");
            }

            try
            {
                var link = _mapper.Map<Link>(linkViewModel);

                if (linkViewModel.Image == null && linkViewModel.FileName != null)
                {
                    link.FileName = linkViewModel.FileName;
                } 
                else if (linkViewModel.Image != null && linkViewModel.FileName != null)
                {
                    _imageStorage.DeleteImage(linkViewModel.FileName);
                    link.FileName = await _imageStorage.AddImageAsync(linkViewModel.Image);
                }

                await _linkRepository.Update(link);
                _notyfService.Success("Link atualizado com sucesso.");
            }
            catch (UnknownImageFormatException)
            {
                _notyfService.Error("Imagem não suportada! Adicione imagens do tipo JPEG, PNG, BMP ou Webp.");
            }
            catch (Exception ex) 
            {
                _notyfService.Error("Ocorreu um erro ao adicionar o link: " + ex.Message);
            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var link = await _linkRepository.GetLinkAsync(id);
            if (link == null)
            {
                return Json(new { message = "Link não encontrado!" });
            }

            return PartialView("_Delete", link);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            try
            {
                var link = await _linkRepository.GetLinkAsync(id);

                if (link == null)
                {
                    _notyfService.Error("link não encontrado!");
                    return RedirectToAction("Index");
                }

                _imageStorage.DeleteImage(link.FileName);

                await _linkRepository.DeleteAsync(link);
                _notyfService.Success("Link removido com sucesso.");
            }
            catch (Exception ex)
            {
                _notyfService.Error("Ocorreu um erro ao remover o link: " + ex.Message);
            }

            return RedirectToAction("Index");
        }
    }
}

LinkHub/Controllers/LogsController.cs
using LinkHub.Data;
using LinkHub.Services;
using LinkHub.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json.Linq;

namespace LinkHub.Controllers
{
    [Authorize(Roles = "Admin")]
    public class LogsController : Controller
    {
        private readonly LogService _logService;

        public LogsController(LogService logService)
        {
            _logService = logService;
        }

        public IActionResult Index(DateTime? startDate, DateTime? endDate, int logLevel)
        {
            var logs = _logService.GetLogs();

            if (startDate.HasValue)
            {
                logs = logs.Where(log => log.Timestamp.HasValue && log.Timestamp.Value.Date >= startDate.Value.Date).ToList();
            }

            if (endDate.HasValue)
            {
                logs = logs.Where(log => log.Timestamp.HasValue && log.Timestamp.Value.Date <= endDate.Value.Date).ToList();
            }

            if (logLevel != 0)
            {
                logs = logs.Where(log => log.Level == logLevel).ToList();
            }

            var logViewModel = new LogViewModel
            {
                StartDate = startDate,
                EndDate = endDate,
                LogLevel = logLevel,
                LogEntries = logs
            };

            return View(logViewModel);
        }
    }
}

LinkHub/Controllers/PagesController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using LinkHub.Models;
using LinkHub.Repositories;
using LinkHub.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace LinkHub.Controllers
{
    [Authorize(Roles = "Admin")]
    public class PagesController : Controller
    {
        private readonly IPageRepository _pageRepository;
		private readonly ICategoryRepository _categoryRepository;
		private readonly IUserPagePermissionRepository _userPagePermissionRepository;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly INotyfService _notyfService;

        public PagesController(IPageRepository pageRepository,
			ICategoryRepository categoryRepository,
			UserManager<ApplicationUser> userManager,
            IUserPagePermissionRepository userPagePermissionRepository,
            INotyfService notyfService)
        {
            _pageRepository = pageRepository;
            _categoryRepository = categoryRepository;
            _userManager = userManager;
            _userPagePermissionRepository = userPagePermissionRepository;
            _notyfService = notyfService;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var pages = _pageRepository.GetPages();
            return View(pages);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return PartialView("_Create");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Page page)
        {
            if (!ModelState.IsValid)
            {
                _notyfService.Warning("Preencha todos os campos obrigatórios.");
                return RedirectToAction("Index");
            }

            var existingPage = await _pageRepository.GetPagePerNameAsync(page.Name);
            if (existingPage != null)
            {
                _notyfService.Warning("Já existe uma página com este nome.");
                return RedirectToAction("Index");
            }

            try
            {
                await _pageRepository.AddAsync(page);

				var category = new Category
				{
					Name = "Home",
					PageId = page.Id
				};

				await _categoryRepository.AddAsync(category);
                _notyfService.Success("Página adicionada com sucesso.");
            }
            catch (Exception ex)
            {
                _notyfService.Error("Ocorreu um erro ao adicionar a página: " + ex.Message);
            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var page = await _pageRepository.GetPageAsync(id);
            if (page == null)
            {
                return Json(new { message = "Página não encontrada!" });
            }

            return PartialView("_Edit", page);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Page page)
        {
            if (!ModelState.IsValid)
            {
                _notyfService.Warning("Preencha todos os campos obrigatórios.");
                return RedirectToAction("Index");
            }

            try
            {
                await _pageRepository.Update(page);
                _notyfService.Success("Página atualizada com sucesso.");
            }
            catch (Exception ex)
            {
                _notyfService.Error("Ocorreu um erro ao atualizar a página: " + ex.Message);
            }                       

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Permission(int id)
        {
            var page = await _pageRepository.GetPageAsync(id);
            if (page == null)
            {
                return Json(new { message = "Página não encontrada!" });
            }

            var selectedUserIds = await _userPagePermissionRepository.GetUsersPerPageAsync(id);

            var users = await _userManager.Users.ToListAsync();

            var permissionView = new PermissionViewModel
            {
                PageId = page.Id,
                PageName = page.Name,
                Users = users,
                SelectedUserIds = selectedUserIds
            };

            return PartialView("_Permission", permissionView);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Permission(PermissionViewModel permission)
        {
            try
            {
                var pageId = permission.PageId;
                var userIds = permission.SelectedUserIds;

                if (userIds != null)
                {
                    await _userPagePermissionRepository.Update(pageId, userIds);
                } 
                else
                {
                    await _userPagePermissionRepository.DeleteAllPagePermissions(pageId);
                }

                _notyfService.Success("Permissões atualizadas com sucesso.");
            }
            catch (Exception ex)
            {
                _notyfService.Error("Não foi possivel atualizar as permissões da página: " + ex.Message);
            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var page = await _pageRepository.GetPageAsync(id);
            if(page == null)
            {
                return Json(new { message = "Página não encontrada!" });
            }

            return PartialView("_Delete", page);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            try
            {
                await _pageRepository.Delete(id);
                _notyfService.Success("Página removida com sucesso.");
            }
            catch (Exception ex)
            {
                _notyfService.Error("Ocorreu um erro ao remover a página: " + ex.Message);
            }
            
            return RedirectToAction("Index");
        }
    }
}

LinkHub/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LinkHub</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/LinkHub.styles.css" asp-append-version="true" />
    <link href="~/lib/DataTables/datatables.min.css" rel="stylesheet">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link href="~/lib/select2/css/select2.min.css" rel="stylesheet">
    <link href="~/lib/select2/css/select2-bootstrap-5-theme.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/notyf@3/notyf.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-success border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand text-white" asp-area="" asp-controller="Home" asp-action="Index">LinkHub</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">
                                <i class="fas fa-home"></i> Home
                            </a>
                        </li>
                        <partial name="_LoginAdminEditor.cshtml" />
                        <partial name="_LoginAdmin.cshtml" />
                    </ul>
                    <ul class="navbar-nav">
                        <li class="navbar-text text-white">
                            @if (User.Identity != null && User.Identity.IsAuthenticated)
                            {
                                <a class="text-white" asp-area="" asp-controller="Account" asp-action="Profile">
                                    @if (Context.Items["FullName"] != null)
                                    {
                                        <span>@Context.Items["FullName"]</span>
                                    }
                                </a>
                            }
                        </li>
                        <li class="nav-item text-white">
                            <form id="logout" method="post" asp-controller="Account" asp-action="Logout">
                                <a href="#" class="nav-link text-white" onclick="document.getElementById('logout').submit();">
                                    <i class="fas fa-sign-out-alt"></i> Sair
                                </a>
                            </form>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container text-center">
            &copy; 2024 - LinkHub - IFSertãoPE Campus Floresta
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/DataTables/datatables.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.4/moment.min.js"></script>
    <script src="https://cdn.datatables.net/plug-ins/1.13.5/sorting/datetime-moment.js"></script>
    <script src="https://cdn.datatables.net/rowGroup/1.1.0/js/dataTables.rowGroup.min.js"></script>
    <script src="~/lib/select2/js/select2.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/notyf@3/notyf.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await Component.InvokeAsync("Notyf")
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

LinkHub/Views/Shared/_LayoutLinks.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LinkHub</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/LinkHub.styles.css" asp-append-version="true" />
    <link href="~/lib/DataTables/datatables.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-light bg-success border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <div class="d-flex w-100 justify-content-between align-items-center">
                    <div>
                        <h3 class="text-white">
                            LinkHub
                        </h3>
                    </div>
                    <div class="mx-auto text-center">
                        <h3 class="text-white">
                            @ViewData["Page"]
                        </h3>
                    </div>
                    <div class="me-2">
                        <input type="text" id="searchInput" class="form-control form-control-sm" placeholder="Buscar..." onkeyup="filterLinks()" />
                    </div>
                    <div>
                        @if (Context.Items["FullName"] != null)
                        {
                            <div class="dropdown">
                                <a class="dropdown-toggle text-white" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
                                    @Context.Items["FullName"]
                                </a>

                                <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                                    <li><a class="dropdown-item" asp-controller="Home" asp-action="Index">Admin</a></li>
                                    <li><a class="dropdown-item" asp-controller="Account" asp-action="Profile">Perfil</a></li>
                                    <li>
                                        <form asp-controller="Account" asp-action="Logout" method="post" style="display:inline;">
                                            <button type="submit" class="dropdown-item">Sair</button>
                                        </form>
                                    </li>
                                </ul>
                            </div>
                        }
                        else
                        {
                            <a class="nav-link text-white" asp-area="" asp-controller="Account" asp-action="Login">
                                <i class="fas fa-sign-out-alt"></i> Entrar
                            </a>
                        }
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container text-center">
            &copy; 2024 - LinkHub - IFSertãoPE Campus Floresta
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/links-filter.js" asp-append-version="true"></script>
    <script src="~/lib/DataTables/datatables.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

LinkHub/Views/Shared/_LayoutLogin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - LinkHub</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/login.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/LinkHub.styles.css" asp-append-version="true" />
</head>

<body>
	<section class="w-100">
		<div class="container h-100">
            @RenderBody()						
		</div>
	</section>

	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

LinkHub/Views/Shared/_LayoutPageNotFound.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LinkHub</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />    
    <link rel="stylesheet" href="~/LinkHub.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-light bg-success border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <div class="d-flex w-100 justify-content-between">
                    <div class="mx-auto text-center">
                        <h3 class="text-white">
                            LinkHub
                        </h3>
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container text-center">
            &copy; 2024 - LinkHub - IFSertãoPE Campus Floresta
        </div>
    </footer>

    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>    
</body>
</html>

LinkHub/Views/Shared/_LoginAdmin.cshtml
@using LinkHub.Models;
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

@if (SignInManager.IsSignedIn(User))
{
    @if (User.IsInRole("Admin"))
    {
        <li class="nav-item">
            <a class="nav-link text-white" asp-area="" asp-controller="Pages" asp-action="Index">
                <i class="fas fa-globe"></i> Páginas
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-white" asp-controller="Users" asp-action="Index">
                <i class="fas fa-users"></i> Usuários
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-white" asp-controller="Logs" asp-action="Index">
                <i class="fas fa-tasks"></i> Logs
            </a>
        </li>
    }
}

LinkHub/Views/Shared/_LoginAdminEditor.cshtml
@using LinkHub.Models;
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

@if (SignInManager.IsSignedIn(User))
{
    @if (User.IsInRole("Admin") || User.IsInRole("Editor"))
    {
        <li class="nav-item">
            <a class="nav-link text-white" asp-area="" asp-controller="Links" asp-action="Index">
                <i class="fas fa-link"></i> Links
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-white" asp-area="" asp-controller="Categories" asp-action="Index">
                <i class="fas fa-list"></i> Categorias
            </a>
        </li>
    }
}